### ISSUE TITLE
ReferenceError: Reflect is not defined

### ISSUE THREAD

**Issue by marnits** [inversify/InversifyJS#115]
I'm trying to achieve the simplest thing which for example is:

```
import { Kernel } from 'inversify';
export let kernel = new Kernel();

kernel.bind('global').toValue(window);
```

and then 

```
import { kernel } from './inversify.config';

let global = kernel.get('global');
```

The result is: 
`Uncaught ReferenceError: Reflect is not defined`

I've tried to use browserify with method `require`, but with no luck.

```
var brwsrfy = browserify({
            standalone : 'test',
            entries: __dirname + '/.tmp/src/test.js',
            debug: true
        })
        .require('./node_modules/inversify/dist/inversify.min.js', { expose: 'inversify'})
        .require('./node_modules/reflect-metadata/Reflect.js');
```

Any suggestions what else can I try?

**Comment by remojansen** [comment]
Hi @marnits please take a look to [this JavaScript example](https://tonicdev.com/remojansen/inversify-2.0.0-alpha.3) . You need to import `reflect-metadata`:

```
require("reflect-metadata");
```

In TypeScript you can do:

```
import "reflect-metadata";
```

Please let me know if it works.

**Comment by marnits** [comment]
I cannot do 

```
import "reflect-metadata";
```

in my ts files. It's not working.

I suggest that you should think about preparing documentation how to use inversify with ES6 modules. I really don't know how to successfully configure your library. In other hand - inversify should inject dependent module be itself. I understand that this is alpha version. I'll change my imports (ES6 modules) for require (Typescript import) and I believe it will works fine, but stable version should work with both of the import mechanisms.

**Comment by remojansen** [comment]
Hi @marnits I understand that the library should import its dependencies. The problem is that these dependencies are optional because they are polyfills. [Importing polyfills is an anti-pattern](http://stackoverflow.com/questions/27870974/what-is-the-correct-way-to-load-polyfills-and-shims-with-browserify#answer-28965677) because it penalizes modern JavaScript environments. So I believe this is a documentation problem more than a problem with the library.

Your issue with: 

```
import "reflect-metadata";
```

Could be that you are missing a reference?

```
/// <reference path="node_modules/reflect-metadata/reflect-metadata.d.ts" />
```

I have created a [page in the wiki](https://github.com/inversify/InversifyJS/wiki/Environment-support-and-polyfills) to document the **environment support and usage of polyfills**. Please let us know if this documentation helped you to solve the problem.

**Comment by marnits** [comment]
Hi @remojansen ! Thank You for providing the document. When I've tried use 

```
import "reflect-metadata";
```

I was getting

```
Uncaught TypeError
```

so I thought that this is related with this import, but not.
This error appears only when I'm trying to use `.toValue()`. For example:

```
kernel.bind('global').toValue(window);
kernel.bind('six').toValue(6);
```

When I'm getting this values from kernel, it prompts `Uncaught TypeError`. Probably it's because I'm doing something wrong - nevermind. 

The problem with Reflect has gone - thank You for your help.

**Comment by RichardJECooke** [comment]
This was super confusing. Please put these lines in your homepage documentation at the top:

Run: `npm install reflect-metadata@0.1.3`
Add to your main .ts file: `import 'reflect-metadata';`

**Comment by remojansen** [comment]
Hi @RichardJECooke in the home page we have a [note about the environment](https://github.com/inversify/InversifyJS/issues/115) that links to the [Environment support and polyfills](https://github.com/inversify/InversifyJS/blob/master/wiki/environment.md) page. 

Is that not enough? Can you please let us know what parts of the docs are confusing? We will try to improve the docs, also if you want you can suggest changes to the docs sending a PR. Thanks!

**Comment by RichardJECooke** [comment]
No, that light grey note is not enough. 

Firstly, because most users assume that a recent version of Node.js is a modern Javascript engine & so wouldn't click to read anything more.

Secondly, because your front page 'hello world' app should show as few as possible, but all necessary, commands to get your app to run. 
In Inversify's case this means including the instruction to install reflect-metadata - or 99% of users on Node will find the basic Inversify app fails for them.

**Comment by RichardJECooke** [comment]
Oh, and sorry, no time for a PR right now - it's just those two lines 'npm install...' though that must be included.

**Comment by remojansen** [comment]
I have created [an issue](https://github.com/inversify/InversifyJS/issues/198) to improve the installation  docs.
