### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by julienvedebe** [inversify/InversifyJS#1165]
Hi i'm currently migrating a report generator made in C# to TypeScript.

I'm using inversify to inject module that reports needs (multiple API for data, XLS lib ...)

I'm also use inversify-agenda to handle multiple tasks.

It's on the good way but now I'm facing some questions about how to implement something

In C# I have a reportBase class witch do basic things for any reports like enumerate objects, get the template of the report ...

And I have several reports that extends that reportBase and have to implement some abstract function defined in reportBase like what we do with each objects.

So for example reportBase iterate each objects and call processObject or the report being used.

reportBase also provide some delegates to have some kind of hooking like beforeObject, afterObject ...

I'm thinking how to get a similar process with just inject my first idea was to use a provider in my main loop to load the correct module corresponding to my current report and then pass the object itself to baseReport using a method.

Second idea is to use rebind and have some currentReport mapped to the report I want and then let things injected in baseReport and process it.

Maybe I have to use inheritance like in C# and just inject the report.

Maybe i'm totally wrong with everything and IOC is not for that kind of things if someone could point me on the right direction.

Many thanks for any help on that

**Comment by notaphplover** [comment]
5 years later...

Mhmm, after reading your issue, I honestly believe it's not related to IoC. I mean, the key to solve your problem is not IoC. What you're describe is commonly solved using a [factory](https://refactoring.guru/design-patterns/factory-method).

You might have a `ReportFactory` able to provide any kind of report. This class might probably rely on instances of classes `SpecificReportABuilder` and `SpecificReportBBuilder` which would probably extend `BaseReportBuilder`.

You might load them in the container like this:

```ts
import { container } from 'inversify'

import { SpecificReportABuilder } from 'path/to/your/module';
import { SpecificReportBBuilder } from 'path/to/your/module';
import { ReportFactory } from 'path/to/your/module';

const container: Container = new Container();

container.load(SpecificReportABuilder).toSelf();
container.load(SpecificReportBBuilder).toSelf();
container.load(ReportFactory).toSelf();

const reportFactory: ReportFactory = container.get(ReportFactory); // it injects SpecificReportABuilder and SpecificReportBBuilder
```

Closing the issue now
