### ISSUE TITLE
Where do we actually need @injectable ? And why `container.get` ?

### ISSUE THREAD

**Issue by haoadoreorange** [inversify/InversifyJS#1211]
Sorry for posting a question here, I couldn't find an answer so...
The code example in wiki have something like this

```
@injectable()
class Katana implements Weapon {
    public hit() {
        return "cut!";
    }
}

@injectable()
class Shuriken implements ThrowableWeapon {
    public throw() {
        return "hit!";
    }
}

@injectable()
class Ninja implements Warrior {

    private _katana: Weapon;
    private _shuriken: ThrowableWeapon;

    public constructor(
	    @inject(TYPES.Weapon) katana: Weapon,
	    @inject(TYPES.ThrowableWeapon) shuriken: ThrowableWeapon
    ) {
        this._katana = katana;
        this._shuriken = shuriken;
    }

    public fight() { return this._katana.hit(); }
    public sneak() { return this._shuriken.throw(); }

}
```
So far as I understand, whenever the container needs to instantiate a class, it must have `@injectable`.

But then is the name a bit misleading ? We don't need to inject `Ninja` anywhere, so it makes no sense having `@injectable`

Also, as a side question, what it the reason behind designing `container.get` ? why can't we just instantiate the class the usual way (aka `new Class()`) and have the `@inject` calling the container to know what is the bind type ?

**Comment by BANOnotIT** [comment]
> Also, as a side question, what it the reason behind designing container.get ? why can't we just instantiate the class the usual way (aka new Class()) and have the @inject calling the container to know what is the bind type ?

In fact [we can instance classes in usual way](https://github.com/inversify/InversifyJS/blob/master/wiki/property_injection.md#when-we-cannot-use-inversifyjs-to-create-an-instance-of-a-class). But I can suggest you to dive into sources to understand what's behind `@injectable` and why we need `container.get`.

**Comment by biogin** [comment]
If a class is decorated with `@Injectable` then it is INJECTABLE as far as inversify concerned. It's kinda self-descriptive. If you want inversify to instantiate objects for you then you tell it to do so by making it `@Injectable` into other classes. 
The reason behind `container.get` is because "newing" things all around your code can (and will) become messy, hard to test and maintain. When you call `const a = new Class();`  you sort of a see it right away that there is an unnecessary coupling between variable `a` and `Class();` Any changes to Class() would require you to change the code around `a`, which already IS an alert that something is not right. Hope that makes sense.
