### ISSUE TITLE
Missing required @inject or @multiInject  -  Inject in contructor is not wprking ( and hard to test) - dynamicvalue is a solution?

### ISSUE THREAD

**Issue by johnico** [inversify/InversifyJS#1215]
I could not inject into the constructor, only as private property  ( React app)
I got  this error:
`or: Missing required @inject or @multiInject annotation in X: argument 0 in class`

I see this issue here and I did not manage to fix it :
https://github.com/inversify/InversifyJS/issues/1004

so I use the private property but this is very hard to test, i did not manage to test it with JEST 

so I manage to create bind like that :

```
// Api service
container.bind<IApi>(TYPES.Api).toDynamicValue(() => {
  const logger = container.get<ILogger>(TYPES.Logger);
  const config = container.get<IConfig>(TYPES.ConfigService);
  return new Api(config, logger);
});

```

and now in the API service, I can inject services  in the constructor and then in jest I can just mock the constructor objects 

is it a good solution ? is it still a singleton? 
what toDynamicValue is realy mean?

what is the difference between toDynamicValue to simple bind

**Comment by alanyong91** [comment]
problem still persists after 1 year

**Comment by notaphplover** [comment]
@johnico the [issue](https://github.com/inversify/InversifyJS/issues/1004) you mention is related to a bundler conifg issue, unrelated to inversify. In order to fix the issue I'd need a minimum reproduction code via [codesandbox](https://codesandbox.io) or any similar platform. A reproduction repository is another valid choice, as long as it contains a minimal reproduction of the issue.

I'm closing the issue now, feel free to provide the reproduction and I'll happilly reopen the issue.
