### ISSUE TITLE
noImplicitAny

### ISSUE THREAD

**Issue by rashtao** [inversify/InversifyJS#125]
When using `noImplicitAny: true` I get the following error:

``` sh
inversify.d.ts(76,9): error TS7010: 'addPlan', which lacks return-type annotation, implicitly has an 'any' return type.
```

**Comment by remojansen** [comment]
HI @rashtao thanks for reporting. We will fix this as soon as we can. All we need to do is change [this line](https://github.com/inversify/InversifyJS/blob/master/tsconfig.json#L11) and fix compilation errors that will raise. So it should be a quick fix.

**Comment by jamesadarich** [comment]
I can pick this one up later today @remojansen  :)

**Comment by remojansen** [comment]
Hi @jamesrichford that would be great :smile: I will assign it to you.

**Comment by jamesadarich** [comment]
Looks like we've got quite a few implicit anys - gonna go through the solution and rework them to keep them nicely typed all the way through and then turn on noImplicitAnys on the compiler if all happy with that?

Also I've noticed a "documentation" folder that's appeared in my build but is not in the repo and not in the gitignore. I've added to gitignore for now so I don't accidentally commit, I take it this shouldn't be committed for now?

**Comment by remojansen** [comment]
yes that's right documentation should not be committed. Take your time fixing the implicit `any`s thanks for helping with ti :smile:

**Comment by jamesadarich** [comment]
Hey Remo,

Looks like we've got some linting issues on the import export portion of inversify:

![image](https://cloud.githubusercontent.com/assets/8244919/13789093/753b3202-eada-11e5-8516-52fa2fa93a62.png)

That relates to:

![image](https://cloud.githubusercontent.com/assets/8244919/13789110/87c1f190-eada-11e5-973a-3e0f1eb23b95.png)

in **./src/inversify.ts**

Is this being resolved elsewhere or do we want to resolve it in this fix?

Also another issue I have detected as a part of removing implicit anys:

in **./src/activation/decorator_utils.ts**

```
function _decorate(decorators: ClassDecorator[], target: Function) {
    Reflect.decorate(decorators, target);
}

function _param(paramIndex: number, decorator: ParameterDecorator): ClassDecorator {
    return function (target: Object, key: string | symbol) { decorator(target, key, paramIndex); };
}

// Allows VanillaJS developers to use decorators:
// decorate(inject("IFoo", "IBar"), FooBar);
// decorate(paramNames("foo", "bar"), FooBar);
// decorate(named("foo"), FooBar, 0);
// decorate(tagged("bar"), FooBar, 1);
function decorate(
    decorator: (ClassDecorator|ParameterDecorator),
    target: any,
    parameterIndex?: number): void {

    if (typeof parameterIndex === "number") {
        _decorate([_param(parameterIndex, decorator)], target);
    } else {
        _decorate([decorator], target);
    }
}
```

I believe this is how it should be typed but I am getting an issue coming out as `_param` does not return a `ClassDecorator` because it has the key argument still in it. Should this be rewritten to:

```
function _decorate(decorators: ClassDecorator[], target: Function) {
    Reflect.decorate(decorators, target);
}

function _param(key: string | symbol, paramIndex: number, decorator: ParameterDecorator): ClassDecorator {
    return function (target: Object) { decorator(target, key, paramIndex); };
}

// Allows VanillaJS developers to use decorators:
// decorate(inject("IFoo", "IBar"), FooBar);
// decorate(paramNames("foo", "bar"), FooBar);
// decorate(named("foo"), FooBar, 0);
// decorate(tagged("bar"), FooBar, 1);
function decorate(
    decorator: (ClassDecorator|ParameterDecorator),
    target: any,
    key?: string | symbol,
    parameterIndex?: number): void {

    if (typeof parameterIndex === "number") {
        _decorate([_param(key, parameterIndex, decorator)], target);
    } else {
        _decorate([<ClassDecorator>decorator], target);
    }
}
```

**Comment by jamesadarich** [comment]
On second thought probably should null out the key property from the `ParameterDecorator` as VanillaJS users are just decorating the class and pointing towards a specific index so the key is inconsequential in our context.

So...

```
function _decorate(decorators: ClassDecorator[], target: Function) {
    Reflect.decorate(decorators, target);
}

function _param(paramIndex: number, decorator: ParameterDecorator): ClassDecorator {
    return function (target: Object) { decorator(target, null, paramIndex); };
}

// Allows VanillaJS developers to use decorators:
// decorate(inject("IFoo", "IBar"), FooBar);
// decorate(paramNames("foo", "bar"), FooBar);
// decorate(named("foo"), FooBar, 0);
// decorate(tagged("bar"), FooBar, 1);
function decorate(
    decorator: (ClassDecorator|ParameterDecorator),
    target: any,
    parameterIndex?: number): void {

    if (typeof parameterIndex === "number") {
        _decorate([_param(parameterIndex, decorator)], target);
    } else {
        _decorate([<ClassDecorator>decorator], target);
    }
}
```

Thoughts?

**Comment by remojansen** [comment]
@jamesrichford thanks for working on this.

# About the tslint issue

 I use the VS Code tslint plugin and I get that error:

![untitled](https://cloud.githubusercontent.com/assets/10656223/13807855/4d985000-eb5b-11e5-83cb-254158d64d5f.png)

However when I use gulp-tslint the error is gone. So it must be the version of tslint? I [have created an issue](https://github.com/Microsoft/vscode-tslint/issues/35) but it is likely to escalate to the tslint project... One thing I have notice is that the global tslint influences on this my global tslint package is `tslint@3.3.0` so maybe try to update gulp-tslint and the global tslint package.

# About `any` issues

The functions `_param` and ``__decorate` are based on the TypeScript pollifyll for decorators. I think target shoud have the same type (probably `any`), in your example it uses 3 types:

![untitled](https://cloud.githubusercontent.com/assets/10656223/13808595/d057399a-eb5e-11e5-98e7-64712bf79670.png)

Go to [this link](http://bit.ly/1RlUcIq) and look at the javascript output.

The function _param cannot change from this:

```
function (paramIndex, decorator) {
    return function (target, key) { decorator(target, key, paramIndex); }
};
```

We can use hard-coded null for the key as you have said. My fault here because I haven't explain this yet but in the future we will probably explore implementing method and properties injections and we will then need the key. So we can choose to set it as null  for now or leave it as it is right now?

The function __decorate has been simplified from:

```
function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
```

to

```
function _decorate(decorators, target) {
    Reflect.decorate(decorators, target);
}
```

Because in inversify we are sure that Reflect is available and we are sure that method and property decorators are not allowed (for now). 

I'm going to try to take a look to help you but I have little time this week so I can't promise :(

**Comment by remojansen** [comment]
Hi @jamesrichford  I took a look to this and I ended up finishing it. As you said it ended up being much more work that expected. Thanks for helping me with it. https://github.com/inversify/InversifyJS/pull/129

@rashtao thanks for reporting the issue. We are trying to go into beta an any kind of issues reported are more than welcome. This is now fixed and will be released soon please keep an eye on the releases.
