### ISSUE TITLE
Libraries using inversify require inclusion of libraries dependencies

### ISSUE THREAD

**Issue by dkhunt27** [inversify/InversifyJS#1257]
When using libraries that use inversify, i need to include the library's dependencies and possible IOC setup in my main code.  For example, if prog-c uses lib-b which is using inversify... in prog-c, i need to include axios which lib-b uses.  Or when lib-b uses lib-a which also uses inversify.  In prog-c, i need to include the IOC to setup lib-a-service which should be done in lib-b.  I am assuming the libraries' containers and/or my main prog need to some how separate (namespace/modules) their IOCs but unsure how to do that.

## Expected Behavior
I would expect that included libraries dependencies and IOC setup would not need to be also included in the main code accessing it... unless it needs to inject a provider of some sort.

## Current Behavior
main code needs to included libraries dependencies/IOC setup

## Steps to Reproduce (for bugs)
I created a simple example of the issue I am seeing.
https://github.com/dkhunt27/inversify-example

## Your Environment
Using inversify v5.0.1
https://github.com/dkhunt27/inversify-example

**Comment by notaphplover** [comment]
Hi @dkhunt27, I've had a look to your example. In your example, if you do not provide the `prog-c`'s container a way to get the bindings, yes, you have do define them again. Fortunatelly, there are several ways to deal with it.

### Use ContainerModules
 See [docs](https://github.com/inversify/InversifyJS/blob/master/wiki/container_modules.md) for additional information.

If `lib-a` provides a `ContainerModule`, lib-b can use it to bind whatever it needs

``` Typescript
import { ContainerModule, interfaces } from 'inversify';
import { libAContainerModule } from 'libA';

export const libBContainerModule: ContainerModule = new ContainerModule(
  (
    bind: interfaces.Bind,
    unbind: interfaces.Unbind,
    isBound: interfaces.IsBound,
    rebind: interfaces.Rebind,
  ) => {
    libAContainerModule.registry(bind, unbind, isBound, rebind);

    // Add lib-b bindings
    ...
  }
);
```

And prog-c could receive the `lib-b` container module in order to load it:

```Typescript
import { Container } from 'inversify';
import { libBContainerModule } from 'libB';

export const container: Container = new Container();

container.load(libBContainerModule);

```

This way there's no need to duplicate bindings. I hope it helps you

### Alternatives
I personally think propagating ContainerModules is the best way to do it, but you could try lazy injection or `autoBindInjectable` option enabled (see [docs](https://github.com/inversify/InversifyJS/blob/master/wiki/container_api.md#autobindinjectable) for more details)

**Comment by dkhunt27** [comment]
awesome, thanks notaphplover
