### ISSUE TITLE
[Question] Do you encourage using Symbols all the time or only for interfaces?

### ISSUE THREAD

**Issue by Jeff-Tian** [inversify/InversifyJS#1303]
Hi, a question about the programming taste: Do you encourage using Symbols all the time or only for interfaces?

We know for interfaces we have to define the symbol for the interface as type:

```
export const xxxType = Symbol.for("xxxType")

@injectable()
export interface XxxInterface {
}

container.bind<XxxInterface>(xxxType).to(XxxInterface)

@injectable()
export class someClass {
  constructor(@inject(xxxType) private readonly xxxInstance: XxxInterface) {
  }
}
```

But for class we might write less code as 

```
@injectable()
export class XxxClass {
}

container.bind(XxxClass).to(XxxClass)

@injectable()
export class someClass {
  constructor(private readonly xxxInstance: XxxClass) {
  }
}
```

From your official point of view, is the above code encouraged? Or do we need to define the symbols for the `xxxClass`, too?

Thanks in advance!

**Comment by notaphplover** [comment]
Hi @Jeff-Tian I cannot give you an official point of view. I can only give you my opinion.

In my opinion, there's no answer in a general scenario. Any argument provided could be invalid in certain scenarios (some developers use inversify for testing purposes, for example), but it's true the vast amount of projects uses inversify as a DI container.

Typescript interfaces does not exist at runtime, so it's not possible to bind a service identifier to an interface, maybe you are interested on binding services which implements interfaces instead:

```Typescript
import { inject, injectable, Container } from 'inversify';

const fooValueServiceIdentifier = Symbol('fooValueServiceIdentifier');

interface IA {
  foo: string;
}

@injectable()
class A implements IA {
  @inject(fooValueServiceIdentifier)
  public foo: string;
}

const container = new Container();

/* 
 * Should I go
 * 
 * container.bind(A).to(A);
 * 
 * or
 * 
 * const iaServiceIdentifier = Symbol(iaServiceIdentifier);
 * container.bind(iaServiceIdentifier).to(A);
 * 
 */
```

If you are using a DI container, you probably have an OOP based project. It's common to follow SOLID in these scenarios. If you are trying to follow the interface segregation principle, I think using symbols would be a better approach since they help you depend on stuff unrelated to your concretions (classes).

Having said that, I think the project's architect is the one who really has the key to answer this question.

**Comment by Jeff-Tian** [comment]
Thank you @notaphplover !
