### ISSUE TITLE
Supporting Modules [toValue binding]

### ISSUE THREAD

**Issue by pixelshaded** [inversify/InversifyJS#19]
Is there anyway to use the container to inject commonjs modules in to your classes as well? Based on the .d.ts, whatever you pass in as the implementation type must have a constructor. Essentially, I would like to use the container to inject modules like express in to the constructors of my classes.

Also, is there any way to support dependencies with callbacks? What if a class needs to do some IO ops when it is being constructed. I would guess these needs to be synchronous, otherwise the container might inject the dependency before its ready.

**Comment by remojansen** [comment]
HI @pixelshaded sorry for the late reply, I had a crazy busy summer. I've been thinking about a few changes that I want to do to InversifyJS and I like your suggestion, I will do everything I can to support both modules and Async injections. I never though about modules by async was on my plans already: https://github.com/inversify/InversifyJS/issues/16

Is going to take me a while because I have to do some analysis about a few complex things but I will keep you updated. Thanks for your feedback :)

**Comment by remojansen** [comment]
Implementation of Inject "ToPromise" and "ToValue" (can be used to inject a module) is in progress...

**Comment by pixelshaded** [comment]
nice. ty

**Comment by remojansen** [comment]
Closing this issue because we are going to track it [here](https://github.com/inversify/InversifyJS/issues/70)
