### ISSUE TITLE
Property injection decorator without kernel

### ISSUE THREAD

**Issue by rashtao** [inversify/InversifyJS#275]
All the examples about `Property injection`  (documented [here](https://github.com/inversify/InversifyJS/blob/master/wiki/property_injection.md)) use an instance of the `Kernel` to create the decorator:

``` js
let kernel = new Kernel();
let inject = makePropertyInjectDecorator(kernel);
// ...
// ... use @inject for Property injection
// ...
```

But this introduces a dependency on one specific instance of `kernel`, so breaking the IoC principle.

Is there a way to avoid it? 

An example to clarify: I am creating an HTTP server framework and want to leave to the user the responsibility to:
- create the kernel 
- bind the framework modules 
- bind configurations 

So the framework library contains:

``` js
@inject("HttpConfig")
class HttpServer{
     // use HttpConfig
}
```

where `HttpConfig` is injected in the constructor. The user can use it in this way:

``` js
import {HttpServer} from "framework";
import {Kernel} from "inversify";

let kernel = new Kernel();
kernel.bind("HttpConfig").toValue({"port": 8080});
kernel.bind("HttpServer").to(HttpServer);
```

How can I modify the sample code in order to use `Property injection`?

**Comment by remojansen** [comment]
You could try something like the following in the framework:

``` ts
function getHttpServer(kernel: inversify.interfaces.Kernel) {

    let pInject = makePropertyInjectDecorator(kernel);

    @injectable()
    class HttpServer {

        @pInject("HttpConfig")
        public httpConfig: HttpConfig;

    }

   return HttpServer;
}
```

And then users would be able to do:

``` ts
import {getHttpServer} from "framework";
import {Kernel} from "inversify";

let kernel = new Kernel();
let HttpServer = getHttpServer(Kernel);
kernel.bind("HttpConfig").toValue({"port": 8080});
kernel.bind("HttpServer").to(HttpServer);
```

We adde property injection support because it was needed in some cases (e.g working with React) but if you could you should avoid it. I learned almost everything I know about DI and IoC in the book [Dependency Injection in .NET](https://books.google.ie/books/about/Dependency_Injection_in_NET.html?id=lnOqcQAACAAJ&source=kp_cover&redir_esc=y&hl=en) and I remember that the author recommended to use constructor injection always as first option.

I've been also able to find some reasons at [SO](http://stackoverflow.com/questions/1503584/dependency-injection-through-constructors-or-property-setters):

> If the class cannot do its job without the dependency, then add it to the constructor. The class needs the new dependency, so you want your change to break things. Also, creating a class that is not fully initialized ("two-step construction") is an anti-pattern (IMHO). If the class can work without the dependency, a setter is fine.

Please let me know if you have more questions or if this issue can be closed.

**Comment by rashtao** [comment]
Thanks for the response. I agree that using constructor injection makes everything better, independently from the library/framework/language. For my implementation I am fine with using it.

About the approach that you propose, I think it is almost like using the kernel as `Service Locator` registry. But it would be another design pattern, sometimes considered an anti-pattern!

Maybe you could explicitly clarify in the documentation/examples that setter injection is achieved using the kernel as `Service Locator` registry.

Feel free to close this issue and congrats for your work and help!

**Comment by remojansen** [comment]
No problem. I have added some notes [here](https://github.com/inversify/InversifyJS/blob/master/wiki/property_injection.md#property-injection) so I'm closing this issue now.
