### ISSUE TITLE
@injectable and getAll with react components

### ISSUE THREAD

**Issue by hungdl** [inversify/InversifyJS#382]
I want to create many button components with one base class.
And then get all buttons by using getAll().
But, looks like inversify wants me to decorate React.Component.
It thought error 'Uncaught Error: Missing required @injectable annotation in: ReactComponent'.

How can I have a solve this?

Thanks,

**Comment by lholznagel** [comment]
Did you find a solution? or why is the issue closed.

**Comment by remojansen** [comment]
This answer is probably too late but...

You need to use lazy property injection with [inversify-inject-decorators](https://github.com/inversify/inversify-inject-decorators) because we can't inject into React components via constructor injection. You can learn more at:
- https://github.com/inversify/InversifyJS/blob/master/wiki/property_injection.md
- http://blog.wolksoftware.com/dependency-injection-in-react-powered-inversifyjs
