### ISSUE TITLE
Drop support for bower

### ISSUE THREAD

**Issue by Jameskmonger** [inversify/InversifyJS#41]
At the moment, too much is being distributed with the bower distribution.

Included in the distribution is the TypeScript source, the Karma configuration, and the test files.

The package size could be slimmed down considerably by only distributing the compiled JS, the LICENSE and the bower.json.

**Comment by Jameskmonger** [comment]
I'll get on this as part of #39

**Comment by remojansen** [comment]
@Jameskmonger about bower I think we need to consider something before you spend time working on this. 

I have seen that the community seems to be encouraging the usage of npm instead of bower you can find many articles about it like [this](http://www.symbiotics.co.za/blog/knowledge-share-2/post/is-bower-dead-what-is-jspm-npm-for-client-side-92) or [this](https://gofore.com/ohjelmistokehitys/stop-using-bower/).

So my main question is: what do you guys think, should we fix bower or just stop using it?

**Comment by Jameskmonger** [comment]
I think stop using it, it's a lot of work to maintain multiple package managers.

**Comment by remojansen** [comment]
I also think that stop using it sounds better. What do you think @jamesrichford ?

**Comment by jamesadarich** [comment]
Just investigated how many downloads inversify has on bower and this probably sways my opinion here.

![image](https://cloud.githubusercontent.com/assets/8244919/12484728/868b8694-c053-11e5-86c2-826476c6548c.png)

I think that all these package managers are lovely for competition and driving people forward but literally we're making work that is not used by anyone so drop it for now and someone can always raise a support bower/jspm etc. issue if they need it. :)

**Comment by remojansen** [comment]
Cool so we are going to drop support for bower. I'm going to change the title of the issue.
