### ISSUE TITLE
Add AMD bundle to the NPM package

### ISSUE THREAD

**Issue by abettadapur** [inversify/InversifyJS#419]
The InversifyJS NPM package does not ship a dist/inversify.js AMD bundle. This means I cannot use this library with tools such as RequireJS. 
Could the package include this bundled AMD version of the library so I don't have to bundle it myself?

**Comment by remojansen** [comment]
Hi, Alex thanks a lot for reporting this issue. Require JS needs AMD modules but not a bundled version of the library. We don't have plans to include a bundled version (`dist/inversify`) because we had problems with that in the past. However, I can add a AMD version for you. 

You will then have to create the bundle using the [RequireJS Optimizer](http://requirejs.org/docs/optimization.html). I will include a`amd` folder in the next release. This folder will contain all the InversifyJS source files in AMD format but not bundled.

**Comment by abettadapur** [comment]
Thank you! That will be very helpful

**Comment by remojansen** [comment]
Done by #420 and available on [3.0.0-beta.2](https://github.com/inversify/InversifyJS/releases/tag/3.0.0-beta.2)

**Comment by abettadapur** [comment]
Hi @remojansen, thanks for doing this, I was able to use the AMD library in my project.
Could you do the same for the inversify-inject-decorators library as well?
