### ISSUE TITLE
Restify handlerFactory uses instanceof Promise - too tightly coupled

### ISSUE THREAD

**Issue by mrsimonemms** [inversify/InversifyJS#437]
In the handlerFactory method in server.ts, there is `if (result && result instanceof Promise)` to detect if the response is a Promise. Is it worth changing that to a detection if there is a `.then` function on there so it can be used with other Promise libraries (less of an issue in a TypeScript project, but may be in Vanilla JS)?

## Expected Behavior
Not expecting any change to behaviour except that it'll detect the features not the implementation. This can then be used with a non-native Promise library (eg Bluebird).

## Current Behavior
A Bluebird Promise would be resolved as a callback not a promise

## Possible Solution
Change the if/else statement to this:

```
if (result) {
    if (typeof result.then === "function" && typeof result.catch === "function") {
        // result.then.catch the same as now
    } else if (!res.headersSent) {
        res.send(result);
    }
}
```

## Your Environment

# Stack trace

**Comment by remojansen** [comment]
I think there is no need to change that. Promise libraries are just a temporal thing and at some point we will not need them. I believe it is correct to write the lib in a way that allow us to don't have to worry about which version of Promise is used.

The check `x instance of Promise` should work because Promise should be a global. For example, if you import it from bluebird:

```
import { Promise } from "bluebird";

// ...

let a = Promise.resolve(1);
a instanceof Promise; // true

```

Or form Q:

```
import * as Q from "q";
let Promise = Q.Promise;

// ....

let a = Promise.resolve(1);
a instanceof Promise; // true

```

Authors of other libraries should do the same thing to avoid problems.

Because promises are declared as a global global we don't need to worry about concrete versions.
