### ISSUE TITLE
Is ["dom"] lib really needed?

### ISSUE THREAD

**Issue by svenefftinge** [inversify/InversifyJS#497]
In https://github.com/inversify/InversifyJS#installation

You say we need to add lib "dom", while inversifyJS should work with node.js. Is that lib really needed? If yes, why is it?

**Comment by lholznagel** [comment]
Inversify also works in the browser and I think that needs `dom`.

**Comment by remojansen** [comment]
I'm not 100% sure but I think it was required because it was needed for promises or weak map I can't remember but there was something that was needed :( if you remove it, do you get errors? Feel free to try to remove it from our docs and config https://github.com/inversify/InversifyJS/blob/master/tsconfig.json#L4 and send a PR the CI servers will let us know if it is really needed :)

**Comment by remojansen** [comment]
So I finally got some free time to check this out and "dom" is not required 👍
