### ISSUE TITLE
Add warning "Deprecated injections without @inject"

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#56]
We need to remove the old way of detecting injections (function.toString() + regex).

Can we add:

```
console.log("WARNING! Injections without inject decorator won't be supported in the upcoming releases");
```

**Comment by jamesadarich** [comment]
Great point Remo. If we intend on changing the API then we should definitely notify people. I'm wondering though if the scope is much greater than just the decorators as we intend to make a fair few changes that will affect people's set up.

Perhaps a more general notification for people using 1.x? But then again should we be treating Inversify 1 and 2 as an upgrade or almost different libraries since the changes may be quite large.

Also may be worth thinking of creating a tool to ease the transition to convert existing set ups from 1.x to 2.x?

**Comment by remojansen** [comment]
I don't think there is going to be a lot of incompatibilities. The main problem I can think about is the usage of injections without the `@Inject` decorator but if we use the warning for it should be ok.

I'm planing to do some changes to some names to make the code a bit shorter. For example:

```
kernel.bind(new TypeBinding<FooInterface>("FooInterface", Foo, TypeBindingScopeEnum.Transient));
```

I would like to use:

```
kernel.bind(new Binding<FooInterface>("FooInterface", Foo, BindingScope.Transient));
```

This won't be a big problem because users can create aliases:

```
var TypeBinding = Binding;
var TypeBindingScopeEnum = BindingScope;
```

**Comment by jamesadarich** [comment]
I guess my thought is that constructing a new Binding is a bit redundant and perhaps using the opportunity to redactor to something like

```
kernel.bind<Interface>("Interface").to(Class).with(Binding Scope.Transient)
```

This will cut out the need to create a new binding and pass that in and make the syntax more fluent

**Comment by remojansen** [comment]
:+1:  I was working on [something similar](https://github.com/inversify/InversifyJS/blob/2.0/source/binding/binding.ts). What I did wasn't brilliant... we can take advantage of [this new feature](https://github.com/Microsoft/TypeScript/pull/4910) to do something better.

**Comment by remojansen** [comment]
Release 1.3.0 drops support for injections without ``@Inject` decorator
