### ISSUE TITLE
Update docs for @requestBody

### ISSUE THREAD

**Issue by patrickhousley** [inversify/InversifyJS#606]
## Expected Behavior
Documentation should make mention that `@requestBody` does not return the body unless a body parser middleware is used on the express app. This was honestly an 'oh duh' issue but one that would have saved me some time scratching my head wondering why my property had the entire request object instead of the body.

## Current Behavior
Documentation does not mention the need for body parser middleware.

**Comment by lholznagel** [comment]
Sorry for that.
For me using body parser as middleware in express was a base requirement, feel free to send a PR :)

**Comment by theodesp** [comment]
It's a good idea to write tests for both scenarios as we need to document the side-effects.

**Comment by lholznagel** [comment]
@patrickhousley under [#57](https://github.com/inversify/inversify-express-utils/pull/57) I extended the example with body parser.

@theodesp what do you mean by that? Express does not throw an exception or does something else.

@both Like discussed [here](https://github.com/inversify/InversifyJS/issues/590#issuecomment-312558734), express utils is only a util and supports you building express controllers. We just added some decorators on top of express. Because we don´t change the way express works, I don´t think it is our task to check if the user added a body parser.

Feel free to extend the PR.

**Comment by lholznagel** [comment]
Done in [#57](https://github.com/inversify/inversify-express-utils/pull/57)
