### ISSUE TITLE
Typescript AMD Inheritance Issue

### ISSUE THREAD

**Issue by dunnohowto** [inversify/InversifyJS#610]
## Expected Behavior
Should bind to a property in a derived class

```ts
@inject(SERVICE_IDENTIFIER.INFORMATION_MANAGER_SERVICE) private _roAdapter: IInformationManagerService;
```

## Current Behavior
Can't map property in a derived class. It seams that the mapping is done with a wrong class DerivedClass.prototype == BaseClass

## Possible Solution
I think the problem ist, that the Mapper is searching for the DerivedClass but can't find it because there is only the BaseClass registered. I've tried to debug it and found that GetOrCreateMetadataMap (Reflect.js) is called once with BaseClass and a second time with DerivedClass.

```ts
define(...) {
    ...
    var ElementContext = (function (_super) {
        __extends(ElementContext, _super);

        function ElementContext(options) {
            var _this = _super.call(this) || this;		
            ...			
            return _this;
        }
       
        __decorate([
            inversify_1.inject(Identifier_1.default.INFORMATION_MANAGER_SERVICE), inversify_1.named("strong"),
            __metadata("design:type", Object)
        ], ElementContext.prototype, "_roAdapter", void 0);
		
        return ElementContext;
    }(ElementContextBase_1.ElementContextBase));
    exports.ElementContext = ElementContext;
});`
```
ElementContext.prototype seems to be the the Problem: ElementContext.prototype === ElementContextBase

## Your Environment

* Version used: 4.2.0
* Environment name and version: Chrome 59, node 4.5
* Operating System and version (desktop or mobile): desktop

# Stack trace

**Comment by dunnohowto** [comment]
![image](https://user-images.githubusercontent.com/15001972/28416223-699161f4-6d53-11e7-8469-397e77be22cb.png)
![image](https://user-images.githubusercontent.com/15001972/28416236-7bec5d04-6d53-11e7-8115-a642fc3a804a.png)

**Comment by ecspand** [comment]
Is Inversify anyway thought to work with requirejs? I think i have a general problem here. Modules are loaded before the main and the config file is loaded, cause of the import in this files.

**Comment by dunnohowto** [comment]
I've pushed a small example with my problem. I've tried with lazyInject and without. I think the problem is, that the the hirarchy is broken cause the modules are maybe loaded to early. Or maybe i still do not understand the procedure :(

https://github.com/Bloodjunkie/InversifyTest

I'm deeply gratefull for any help :)

**Comment by dunnohowto** [comment]
Is it not possible or thought to use Inversify in a amd scenario or what could be the problem?

**Comment by remojansen** [comment]
@Bloodjunkie sorry for the very late reply on this issue. InversifyJS has not been designed with AMD support in mind. I can imagine that it is possible to get it to work but these days AMD is very uncommon so investing in it is not worth it.

Also, inheritance is quite complicated to support, we have done everything that we could but the support for inheritance is not as smooth as we would like. Not our fault though because the problems are due to some technical limitations. We, therefore, recommend using composition over inheritance (this is a recommended OOP good practice anyway) and have also created a [wiki pay with some help about common inheritance issues](https://github.com/inversify/InversifyJS/blob/master/wiki/inheritance.md).

I will close this issue as there is not much that we can do to help with either AMD or inheritance.
