### ISSUE TITLE
Question: (inversify-express-utils) How can i use a generic controller as several registered controllers with path info

### ISSUE THREAD

**Issue by mattmeye** [inversify/InversifyJS#632]
Hello, 

how can i use a generic controller class as several registered controllers without creating subclasses like 
    
    @controller('/a')
    class AController extends FooController<A>

Example:

    # a generic class
    class FooController<T> {
        @httpGet('/')
        private get() {
           return 'hey'
        }
    }

    # app
    import { Container } from 'inversify'
    const container = new Container()
    container.bind(...)

    # @controller('/a')
    # FooController<A>

    # @controller('/b')
    # FooController<B>

I have read the documentation: 

> @controllers(...)
> Registers the decorated class as a controller with a root path, and optionally registers any global middleware for this controller.

Would not be better if a instance of a class instead of a class registers as a controller? Or set path via an injectable constructor parameter? I think that a controller class should not determine how it is used.

Many Thanks

**Comment by dcavanagh** [comment]
I don't think that this is possible in typescript 

`FooController<A>` is a type not a class.

**Comment by remojansen** [comment]
@mattmeye TypeScript limits the usage of decorators to classes no instances but I think I get what you are trying to achieve. Many controllers are a simple HTTP CRUD interface for some entity and it would be nice if we could use a generic controller. Instead of having to re-write the same code many times.

I'm closing this issue because we already have an issue to support generic controllers. This is something that I personally want to fix somehow. So you can expect something to happen about it early next year. The issue is https://github.com/inversify/InversifyJS/issues/586
