### ISSUE TITLE
inversify-inject-decorators dts files is obsolete. 

### ISSUE THREAD

**Issue by ae-draft** [inversify/InversifyJS#679]
**inversify-inject-decorators** dts files is obsolete. 
I tried to install `@types/inversify-inject-decorators` and it's correct, but internal dts throw error 
**"TS2694: Namespace 'interfaces' has no exported member 'Container'."**

**Comment by remojansen** [comment]
You don't need to install the typings using npm (they are already included in the npm module)

**Comment by ae-draft** [comment]
Yes, but module typings is obsolete!

**Comment by remojansen** [comment]
- If the `.d.ts` file included in `@types/inversify-inject-decorators` is not working the problem needs to be reported in https://github.com/DefinitelyTyped/DefinitelyTyped. They should flag the file as deprecated.

- If the `.d.ts` file included in `inversify-inject-decorators` is not working then the problem should be reported here. However, I find this unlikely because the `.d.ts` file is auto-generated by the compiler.

You should avoid using `@types/inversify-inject-decorators`. In the [docs](https://github.com/inversify/inversify-inject-decorators#installation) we say:

> The inversify-inject-decorators type definitions are included in the npm module and require TypeScript 2.0.
