### ISSUE TITLE
Config issues with create-react-app

### ISSUE THREAD

**Issue by sremiger1** [inversify/InversifyJS#682]
In the tsconfig.json you require that the developer enters "types": ["reflect-metadata"] as part of the setup.

## Current behavior
Expect the developer to insert `"types": ["reflect-metadata"],` into  tsconfig.json

## Side Effect
Every other type than has to be manually entered
`"types": ["reflect-metadata", "node", "jest", "office-js"],`  With no ability to do `"types": ["reflect-metadata", "*"],`  This I think is a little cumbersome.

## Possible Solution
If you read the documentation on types compiler options [types-typeroots-and-types](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types)  you might be able to configure the install to place it in the @types directory.  This allows the developer to use other types without explicitly naming them.

## Steps to Reproduce (for bugs)
```
create-react-app my-app --scripts-version=react-scripts-ts
cd my-app
npm install inversify reflect-metadata --save
add to tsconfig.json
        //"target": "es5", Duplicate
        //"lib": ["es6", "dom"], Duplicate
        "types": ["reflect-metadata"],
        "module": "commonjs", //orginal esnext
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true

```

**Comment by remojansen** [comment]
Hi, thanks for reporting this issue. We need to investigate this one better it is not the first time that this issue is mentioned to me but it is weird because I've been using this config in many projects and I never experienced this issue. One thing that I just noticed is that everybody experiencing the issue seems to be using `create-react-app` so my guess is that something else is going one in the  `create-react-app` config.

**Comment by remojansen** [comment]
I have spent some time trying to test this but `create-react-app my-app --scripts-version=react-scripts-ts` failed for me. I will close this issue because it seems like a `typescript` or `create-react-app` or config issue not an issue with inversify.
