### ISSUE TITLE
What does toFunction do differently from toConstantValue?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [inversify/InversifyJS#697]
@helenanderson and I were curious. #237 from @remojansen added it in with just this note:

> We can inject functions with `toConstructor` or `toConstantValue` but is not fully correct.

Can this be documented somewhere? [scope.md](https://github.com/inversify/InversifyJS/blob/master/wiki/scope.md) doesn't provide much context on the different kinds of function injections.

**Comment by remojansen** [comment]
They are the same. Check out [this](https://github.com/inversify/InversifyJS/blob/master/src/syntax/binding_to_syntax.ts#L89) line in the code. I added aliases because some people wanted to explicitly remark that a function is going to be injected. We can also say toConstructor for example. A constructor is a function but if what we are trying to inject is not meant to be a constructor it could be misleading. So it is basically a way to describe better what you are trying to do.

**Comment by remojansen** [comment]
Hi @JoshuaKGoldberg can this issue be closed? Thanks!

**Comment by remojansen** [comment]
Closing this issue please feel free to ask more questions. Also, as a reference, if you are wondering about `toConstructor` / `toDynamicValue` / `toFactory` check out the following question on SO 👉 https://stackoverflow.com/questions/46867437/in-inversify-why-to-prefer-constructor-factory-injection-over-todynamicvalue/47055959#47055959
