### ISSUE TITLE
Binding.clone() - flag `activated` is set `false` hiding already created singletons -Why?

### ISSUE THREAD

**Issue by nros** [inversify/InversifyJS#700]
problem description
--------------------

In my application I use temporary containers created with something like:
```
    const temporaryDIContainer = Container.merge(new Container(), parentContainer);
```
All bindings of `temporaryDIContainer` are set to `activated = false`. So in case the parent container has already created a singleton instance, it is ignored and a new instance is created.
```
    const preExistingSingletonInstance = temporaryDIContainer.get("SingletonClass");
```

relevant code lines
-------------------
https://github.com/inversify/InversifyJS/blob/776d88abce107b7b9418ea01429abbf4beb2cee8/src/bindings/binding.ts#L62

The flag `activated` is set to false. Therefore the already created singleton instance in `this.cache` is not used but a new one is created here:
https://github.com/inversify/InversifyJS/blob/776d88abce107b7b9418ea01429abbf4beb2cee8/src/resolution/resolver.ts#L40

**Is there a reason for this behaviour that I am missing? To me this seems wrong.**

**Comment by remojansen** [comment]
@nros it is because `Binding.clone()` is used for the container snapshot feature. When we create a snapshot and restore we want to ensure that the original binding is not mutated. If the new binding shares the singleton value with the old binding a mutation could be possible. Maybe `Binding.clone()` shuld be named `Binding.snapshot()` instead. I would also need to check to ensure that that is the only use case (maybe there is something else that I can't remember).

**Comment by nros** [comment]
OK, I get it, thanks. So I was just mislead by the name.

Meanwhile I was able to use a different solution by utilizing a child container as temporary container. It solved my specific problem and seems the far better solution anyway.

Many thanks for your time and clarification.

**Comment by remojansen** [comment]
No worries :+1: Thanks for using inverisfy :100:
