### ISSUE TITLE
how to work with react

### ISSUE THREAD

**Issue by GiantappMan** [inversify/InversifyJS#807]
## Expected Behavior

work correctly with react component

## Current Behavior

export class Logger2  implements ILogger {}
this work fine

export class Logger2 extends React.Component<AppState, AppState> implements ILogger {}
this get error

**Comment by dcavanagh** [comment]
@DaZiYuan  The code that you provided does not use any Inversify feature.
Please provide some more information and sample code.

What error are you getting?

**Comment by Place1** [comment]
To use inversify with react you need to use lazy injection because the container isn't responsible for constructing your react components, react is.

Have a look at this library: https://github.com/inversify/inversify-inject-decorators

Or this other library that I created to reduce boilerplate as well as provide lazy injection: https://github.com/Place1/inversify-stereotype-decorators

Lazy injection is basically just a new decorator that already knows about the IoC container. This allows the decorator to resolve dependencies itself rather than requiring the class to be created by the container itself, this get you around most of the hurdles in react.

**Comment by GiantappMan** [comment]
I already used typescript-ioc,it seems work
