### ISSUE TITLE
How to decorate external lib with @injectable()

### ISSUE THREAD

**Issue by sergei-rastrigin** [inversify/InversifyJS#866]
I have an external library with a set of classes. 
I want somehow decorate these classes in my module and make them injectable.

## Possible Solution

Right now I do next:
```
import * as libClasses from 'externalLib'
import {injectable} from 'inversify';

Object.keys(libClasses).forEach((field)=> {
  const libClass = libClasses[field];
  const decorator = injectable();
  libClasses[field] = Reflect.decorate([decorator], libClass);
});
```
But it doesn't work.
So, the question is - how I can bind decorator programmatically?

**Comment by rmvermeulen** [comment]
use `decorate`, also from inversify.
```
import { decorate, injectable } from 'inversify'
decorate(injectable(), SomeClass)
```

**Comment by sergei-rastrigin** [comment]
@rmvermeulen Thank you!

**Comment by y-chen** [comment]
How do you inject the library when it's decorated?

**Comment by titusfx** [comment]
@rmvermeulen approach doesn't work if the class has a super.
You could get the super in the following way:

`
const mySuper = Object.getPrototypeOf(SomeClass).constructor;
decorate(injectable(), mySuper)
`

But this didn't work, I believe it is because in runtime you don't have the name of the Super, so it couldn't find it, but curious enough the error of InversifyJS tells me the error with the parent className, for some reason it didn't realize that is the parent
