### ISSUE TITLE
Web-Extensions support?

### ISSUE THREAD

**Issue by TheAifam5** [inversify/InversifyJS#891]
Hey,

I'm writing an web extension for Firefox. I got every time an error:
`TypeError: Reflect.hasOwnMetadata is not a function`

I'm using webpack with `awesome-typescript-loader`.
The `vendor.js` file is always included, also the Reflect is inside of `vendor.js` if:
 - the `index.ts` of the web-extension has `import 'reflect-metadata'`
 - the `webpack.config.ts` contains an entry vendor with all packages used by a probject.

Maybe the web-extension does not allow? :D
I'm using `tsconfig.json` target ES6 with bunch of `libs`. I didn't include `types` because TS finds it automatically.

Regards,
TheAifam5

**Comment by remojansen** [comment]
Hi @TheAifam5 my understanding is that web extensions use a completely independent execution environment form the application environment. This means that the reflect-metadata module needs to be imported from both the app and the extension. Then your next problem is going to be that the extension and the app cannot share memory. So if you want them to be able to talk to each other you are going to need to create a set of serializable messages. I'm afraid we are not going to be able to provide you with much support here because we know very little about extensions. Maybe you can ask at the Mozilla channels https://discourse.mozilla.org/c/add-ons ?  I will close this issue because I don't think we can do anything else.
