### ISSUE TITLE
inversify-restify-utils maintainence

### ISSUE THREAD

**Issue by mgebundy** [inversify/InversifyJS#906]
Is `inversify-restify-utils` still being maintained? I've made 3 PRs that have been accepted and merged, but the package hasn't been tagged or released since November.

What will it take to get a release pushed out? Is there a lack of people willing to maintain it?

**Comment by remojansen** [comment]
Hi @mgebundy the core maintainers are more focused on express than restify because we use it at work everyday. The restify package was contributed by someone outside of the core team. We try to maintain it. Merging PRs and doing releases but we don't actively try to add new features. If you are interested in actively maintainn it to keep it up to date witht he express utils that would be much appreciated. I will do a release at some point later today.

**Comment by remojansen** [comment]
Hi @mgebundy  I have released `inversify-restify-utils@3.4.0`. I should be more active soon, I've been very busy for months trying to finish a book.

**Comment by mgebundy** [comment]
@remojansen cheers, i appreciate you taking the time, good luck with the book!

I'll continue making PRs where needed to that repo, and we'll be happy to take on its maintenance, seeing as we use restify in the majority of our nodejs services.
