### ISSUE TITLE
Inversify-express-utils: Can i use graphql in inversify-express-utils?

### ISSUE THREAD

**Issue by zerox12311** [inversify/InversifyJS#920]
Hi ! I want to use graphql in Inversify-express-utils,but i don't know have any idea to bind to my controller.
Does any example can support?

## Expected Behavior

I expected use decorator to decorate my controller.

**Comment by remojansen** [comment]
Hi @zerox12311, unfortunately, we don't have an example but in theory, there should be no problems with it. You will need to create a controller just like any other controller in `inversify-express-utils`. There are examples of that in the [repo](https://github.com/inversify/inversify-express-utils#step-1-decorate-your-controllers). In graphql, you will need to create one single endpoint. Instead of having multiple controllers with multiple endpoints you will have only one. That controller can have dependencies injected just like any other controller in `inversify-express-utils`.

**Comment by jrhite** [comment]
@zerox12311 In case you haven't figured it out, it is possible. I took a couple wrong turns, but got it working nicely.

The main problem I had was injecting the GraphQL middleware. GraphQL middleware is created via function call which isn't directly injectable in inversify. Something like:

```
@controller('/graphiql', graphqlHTTP({ schema: schema, rootValue: root, graphiql: true }))
class GraphIQLController extends BaseHttpController {
  @httpGet('/')
  public async get() {
    // do stuff
  }
}
```

But our `root` resolver is likely an injectable class:

```
@injectable()
class Resolver {
  constructor(@inject(TYPES.UserRepository) private readonly _userRepository: UserRepository) {
  }

  // ...
}
```

Oops! We can't inject the function. I initially tried the [inject a function recipe](https://github.com/inversify/InversifyJS/blob/master/wiki/recipes.md#injecting-dependencies-into-a-function), but that didn't work out for a variety of reasons, mostly because the injected functions were being injected before my main reference container had a chance to load its dependent modules.

After that misattempt, I quickly found `BaseMiddleware` which makes it all work. My solution looks something sorta like:

```
const TypeDefs = `
  type Query {
    users: [User]
  }

  type User {
    userId: String!
  }
`;

const Schema: GraphQLSchema = buildSchema(TypeDefs);

@injectable()
class Resolver {
  constructor(
    @inject(TYPES.UserRepository) private readonly _userRepository: UserRepository) {
  }

  users() {
    return this._userRepository.getUsers();
  }
}

@injectable()
class GraphQLHttpOptions implements graphqlHTTP.OptionsData {
  graphiql = true;

  constructor(
    @inject(TYPES.Schema) public schema: GraphQLSchema,
    @inject(TYPES.Resolver) public rootValue: Resolver) {
  }
}

@injectable()
class GraphQLHttpMiddleware extends BaseMiddleware {
  private readonly _middleware: graphqlHTTP.Middleware;

  constructor(@inject(TYPES.GraphIQLHttpOptions) options) {
    super();

    this._middleware = graphqlHTTP(options);
  }

  public handler(request: Request, response: Response, next: NextFunction) {
    void this._middleware(request, response);
  }
}

const GraphQLHttpModule = new ContainerModule((bind: interfaces.Bind) => { 
  bind<GraphQLSchema>(TYPES.Schema).toConstantValue(Schema);
  bind<Resolver>(TYPES.Resolver).to(Resolver).inSingletonScope();

  bind<GraphQLHttpOptions>(TYPES.GraphQLHttpOptions).to(GraphQLHttpOptions).inSingletonScope();

  bind<BaseMiddleware>(TYPES.GraphQLHttpMiddleware).to(GraphQLHttpMiddleware).inSingletonScope();
});

@controller('/graphiql', TYPES.GraphQLHttpMiddleware)
class GraphIQLController extends BaseHttpController {
  @httpGet('/')
  public async get() {
  }

  @httpPost('/')
  public async post() {
  }
}

Hope this helps!
```

**Comment by oguimbal** [comment]
FYI I just released a lib that does just that:  https://github.com/oguimbal/inversify-graphql

It does not use inversify-express-utils, but you can integrate it through 

```typescript

const server = new InversifyExpressServer(container);
server.setConfig((app) => {
        // ..... other setup ....
        const srv = new ApolloServer({
            schema: inversifySchema(container, mySchema),
        });
        srv.applyMiddleware({ app, path: '/graphql'});
});
```
