### ISSUE TITLE
Any migration steps to go from v4 to v5?

### ISSUE THREAD

**Issue by pedro-mass** [inversify/InversifyJS#981]
## Expected Behavior

Any docs on this?

## Context

Looking to upgrade dependencies but worried about what I'm bringing in

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

node: 8.10
OS: mac ios

# Stack trace

**Comment by dcavanagh** [comment]
the guid function has been changed to id 
and the property guid has been changed to id on the following interfaces & their implementations 

Binding
Context
Request
Target
Container
ContainerModule
AsyncContainerModule

**Comment by tiagoschenkel** [comment]
The **Public API** changed when the method **guid** was renamed to **id**. Also, instead of returning a **string**, the method is returning a **number**.

```typsecript
let idCounter = 0;

function id(): number {
  return idCounter++;
}

export { id };
```

The version **4.14.0** is actually the version **5.0.0**, at least now is explicit that there is a breaking change. I pointed this out in #882.

I only discovered this problem because **greenkeeper** tried to update the **inversify** dependency on my project, :).

Thank you @dcavanagh for taking care of this!

**Comment by dcavanagh** [comment]
I added the information in #983
